version: "{build}"

os: Windows Server 2012

clone_folder: c:\projects\vim-ci

before_build:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release'
  - git submodule update --init --depth 5

build_script:
  - cd vim/src
  - sed -e "s/\$(LINKARGS2)/\$(LINKARGS2) | sed -e 's#.*\\\\r.*##'/" Make_mvc.mak > Make_mvc2.mak
  - nmake -f Make_mvc2.mak CPU=AMD64 GUI=yes IME=yes MBYTE=yes ICONV=yes DEBUG=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=C:\Python27-x64 PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=C:\Python34-x64
  - .\gvim -u NONE -c "redir @a | ver | 0put a | wq!" ver.txt
  - type ver.txt

test_script:
  - curl https://bitbucket.org/k_takata/vim-ktakata-mq/raw/d62eae94f74a2f18317cec28785c514587bcc9b0/workaround-test100.patch | patch -p2
  - curl https://bitbucket.org/k_takata/vim-ktakata-mq/raw/5912dbd4d0509a80da3c4d1e54f4315f80c421d7/fix-test11-on-windows.patch | patch -p2
  - curl https://bitbucket.org/k_takata/vim-ktakata-mq/raw/93a7594e99cd8601e5bb576bb2fad6632b347845/fix-test86-87-on-windows.patch | patch -p2
  - cd testdir
  - nmake -f Make_dos.mak VIMPROG=..\gvim
